#!/usr/bin/env python

"""Neil's hacking hex viewer"""

# pylint: disable=C0103,C0301,W0702,W0703,W1202,W1203

import argparse
import curses
import datetime
import logging
import math
import mmap
import os.path
import struct
from typing import List,Tuple

logger = logging.getLogger(__name__)

MODE_HEX: int = 0
MODE_ASCII: int = 1

def _parse_data_size(arg: str) -> int:
    size = arg

    if size.endswith('K') or size.endswith('k'):
        size = int(size[:-1]) * 1024
    elif size.endswith('M') or size.endswith('m'):
        size = int(size[:-1]) * 1024*1024
    elif size.isdigit():
        size = int(size)
    else:
        raise ValueError("illegal size unit.")

    return size

def _buffer_as_spaced_hex(buffer: bytes) -> str:
    chunks: List[str] = []

    for i in range(0, len(buffer), 4):
        chunks.append(" ".join([f'{b & 0xff:02X}' for b in list(buffer[i:i+4])]))


    return "  ".join(chunks)

def _buffer_as_printable(buffer: bytes) -> str:
    allowed = bytearray(b'0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~ ')

    return "".join([chr(b) if b in allowed else '.' for b in list(buffer)])

def _index_to_position(idx: int, bytes_per_line: int, left_offset: int) -> Tuple[int, int]:
    y = idx // bytes_per_line
    x = idx % bytes_per_line

    x = x * 3 + (x // 4)

    # skip border
    y += 1

    # add left spacing
    x += left_offset + 3

    return [y, x]


def _index_to_ascii_position(idx: int, bytes_per_line: int, left_offset: int) -> Tuple[int, int]:
    y = idx // bytes_per_line
    x = idx % bytes_per_line

    offset = bytes_per_line * 3 + (bytes_per_line // 4)

    # skip border
    y += 1

    # add left spacing
    x += left_offset + 3 + offset

    return [y, x]

def _spinning_cursor():
    while True:
        yield from '|/-\\'

class ScreenSizing:
    """Screen display sizing."""

    def __init__(self, stdscr: 'curses.window', file_size: int):
        self._height, self._width = stdscr.getmaxyx()

        self.data_win_width: int = 42

        self.mark_win_width: int = 42

        self.eval_win_width: int = 42

        if file_size > 2**32:
            self.offset_address_size: int = 12
        else:
            self.offset_address_size: int = 8

    @property
    def data_win_height(self) -> int:
        """Width of data window."""
        return self._height // 3

    @property
    def dump_win_width(self) -> int:
        """Width of dump window."""
        return self._width - self.data_win_width

    @property
    def dump_win_height(self) -> int:
        """Height of dump window."""
        return self._height

    @property
    def mark_win_height(self) -> int:
        """Height of file mark window."""
        return self._height // 3

    @property
    def eval_win_height(self) -> int:
        """Height of struct pattern eval window."""
        return self._height // 3

    @property
    def bytes_per_line(self) -> int:
        """Number of bytes per line to display."""

        bytes_per_line: int = (self.dump_win_width - self.offset_address_size) // 4

        cy,_ =  _index_to_position(bytes_per_line, bytes_per_line, self.offset_address_size)

        if cy > 1:
            bytes_per_line -= 4
        bytes_per_line -= (bytes_per_line % 4)

        return bytes_per_line

    @property
    def hex_offset(self) -> int:
        """Screen offset where hex bytes begin."""

        return self.offset_address_size + 3

    @property
    def ascii_offset(self) -> int:
        """Screen offset where ascii begins."""

        bytes_per_line: int = self.bytes_per_line

        return (bytes_per_line * 3 + (bytes_per_line // 4)) + self.hex_offset

    @property
    def data_line_length(self) -> int:
        """Lendth of single ling disply of hex bytes."""
        return (self.bytes_per_line * 3) + (self.bytes_per_line // 4)

    @property
    def bytes_per_screen(self) -> int:
        """Maximum number of bytes displayed on the screen."""
        return self.bytes_per_line * (self.dump_win_height-2)

    @property
    def help_win_height(self) -> int:
        """Width of data window."""
        return self._height // 2

    @property
    def help_win_width(self) -> int:
        """Width of dump window."""
        return self._width // 2


    @property
    def help_win_y(self) -> int:
        """Width of data window."""
        return self._height // 4

    @property
    def help_win_x(self) -> int:
        """Width of dump window."""
        return self._width // 4


class ApplicationState:
    """Stores application state."""

    def __init__(self):
        self.cursor_position: int = 0
        self.file_offset: int = 0

        self.mode: int = MODE_HEX
        self.byteorder: str = 'little'

        self.jump_offset: int = 0

        self.ascii_search: str = ''
        self.hex_search: str = b''
        self.struct_eval: str = ''

        self.marks: List[int] = []

    @property
    def data_offset(self) -> int:
        """The actual offset in file."""
        return self.file_offset + self.cursor_position


def _show_help_window(screen_sizing: ScreenSizing):
    help_win = curses.newwin(screen_sizing.help_win_height, screen_sizing.help_win_width, screen_sizing.help_win_y, screen_sizing.help_win_x)
    help_win.box()
    help_win.addstr(0, (screen_sizing.help_win_width // 2) - 2, "Help")

    help_messages: List[Tuple[str, str]] = [
        ("h", "Open help window"),
        ("TAB", "Switch between HEX and ASCII mode"),
        ("ENTER", "Jump to absolute file postion"),
        ("PGUP", "Jump back one screen of data"),
        ("PGDN", "Jump forward one screen of data"),
        ("/", "Search for bytes in HEX mode, or string in ASCII mode"),
        ("j", "Set $JUMP_OFFSET count (as decimal)"),
        ("J", "Set $JUMP_OFFSET count (as hex)"),
        ("SPACE", "Jump forward $JUMP_OFFSET bytes"),
        ("m", "Create new file make at current cursor position"),
        ("M", "Remove last created file mark"),
        ("n", "Jump to next file mark"),
        ("N", "Jump to previous file mark"),
        ("l", "Toggle between little and big endian display mode"),
        ("s", "Set struct eval pattern $STRUCT"),
        ("[", "Jump forward sizeof($STRUCT) bytes"),
        ("]", "Jump backward sizeof($STRUCT) bytes"),
        ("<", "Jump to first byte of file"),
        (">", "Jump to last byte of file"),
        ("q", "Quit"),
    ]


    for i, (keypress, message) in enumerate(help_messages):
        help_win.addstr(3+i, 4, keypress)
        help_win.addstr(3+i, 20, message)

    help_win.refresh()


def main(stdscr: 'curses.window') -> None:
    """The main entry point."""
    argparser = argparse.ArgumentParser()
    argparser.add_argument('-v', '--verbose', help='Verbose output', action='store_true', dest='verbose')
    argparser.add_argument('-q', '--quiet', help='Quiet output', action='store_true', dest='quiet')
    argparser.add_argument('-d', '--debug', help='Debug mode', action='store_true', dest='debug')
    argparser.add_argument('-s', '--search', help='Search block size', type=str, dest='search', default='20M')
    argparser.add_argument('binfile', help='Input binary file', type=str)
    args = argparser.parse_args()

    if args.verbose:
        logging.basicConfig(level=logging.DEBUG, format='[%(process)d] (%(funcName)s) %(message)s')
    elif args.quiet:
        logging.basicConfig(level=logging.ERROR, format='')
    else:
        logging.basicConfig(level=logging.INFO, format='[%(process)d] (%(funcName)s) %(message)s')

    stdscr.clear()

    file_size: int = os.path.getsize(args.binfile)
    screen_sizing = ScreenSizing(stdscr, file_size)

    dump_win = curses.newwin(screen_sizing.dump_win_height, screen_sizing.dump_win_width, 0, 0)
    dump_win.box()

    data_win = curses.newwin(screen_sizing.data_win_height, screen_sizing.data_win_width, 0, screen_sizing.dump_win_width)

    mark_win = curses.newwin(screen_sizing.mark_win_height, screen_sizing.mark_win_width, screen_sizing.data_win_height, screen_sizing.dump_win_width)
    mark_win.box()
    mark_win.addstr(0, (screen_sizing.mark_win_width // 2) - 4, 'File marks')

    eval_win = curses.newwin(screen_sizing.eval_win_height, screen_sizing.eval_win_width, screen_sizing.data_win_height+screen_sizing.mark_win_height, screen_sizing.dump_win_width+0)
    eval_win.box()
    eval_win.addstr(0, (screen_sizing.eval_win_width // 2) - 4, 'Eval')

    # Refresh to display changes
    stdscr.refresh()
    dump_win.refresh()
    data_win.refresh()
    mark_win.refresh()
    eval_win.refresh()

    app_state = ApplicationState()

    search_block_size: int = _parse_data_size(args.search)

    with open(args.binfile, 'rb') as fh:
        with mmap.mmap(fh.fileno(), length=0, access=mmap.ACCESS_READ) as fm:
            while True:
                dump_win.box() # Uses default characters
                dump_win.addstr(0, screen_sizing.dump_win_width//2, os.path.basename(args.binfile))
                dump_win.addstr(screen_sizing.dump_win_height-1, 4, f' 0x{app_state.data_offset:X}/0x{file_size:X}  {math.floor(((app_state.data_offset/file_size) * 100) + 0.5):3d}%')

                data_win.box()
                data_win.addstr(0, (screen_sizing.data_win_width//2) - 4, f'Data ({app_state.byteorder})')

                if app_state.mode == MODE_ASCII:
                    cy, cx = _index_to_ascii_position(app_state.cursor_position, screen_sizing.bytes_per_line, screen_sizing.offset_address_size)
                else:
                    cy, cx = _index_to_position(app_state.cursor_position, screen_sizing.bytes_per_line, screen_sizing.offset_address_size)

                stdscr.move(cy, cx)
                cy, cx = stdscr.getyx()

                for i in range(0, screen_sizing.dump_win_height-2):
                    offset: int = i * screen_sizing.bytes_per_line + app_state.file_offset

                    hex_data = fm[offset:offset+screen_sizing.bytes_per_line]

                    dump_win.addstr(i+1, 1, f'{offset:0{screen_sizing.offset_address_size}X}  {_buffer_as_spaced_hex(hex_data)}')
                    dump_win.addstr(i+1, screen_sizing.data_line_length+screen_sizing.offset_address_size+3, f'{_buffer_as_printable(hex_data)}')

                if app_state.mode == MODE_HEX:
                    sy, sx = _index_to_ascii_position(app_state.cursor_position, screen_sizing.bytes_per_line, screen_sizing.offset_address_size)
                    real_position: int = app_state.data_offset
                    dump_win.addstr(sy, sx, _buffer_as_printable(fm[real_position:real_position+1]), curses.A_BOLD|curses.A_UNDERLINE)
                else:
                    sy, sx = _index_to_position(app_state.cursor_position, screen_sizing.bytes_per_line, screen_sizing.offset_address_size)
                    real_position: int = app_state.data_offset
                    dump_win.addstr(sy, sx, _buffer_as_spaced_hex(fm[real_position:real_position+1]), curses.A_BOLD|curses.A_UNDERLINE)

                int8 = int.from_bytes(fm[app_state.data_offset:app_state.data_offset+1], byteorder=app_state.byteorder, signed=True)
                uint8 = int.from_bytes(fm[app_state.data_offset:app_state.data_offset+1], byteorder=app_state.byteorder, signed=False)
                int16 = int.from_bytes(fm[app_state.data_offset:app_state.data_offset+2], byteorder=app_state.byteorder, signed=True)
                uint16 = int.from_bytes(fm[app_state.data_offset:app_state.data_offset+2], byteorder=app_state.byteorder, signed=False)
                int32 = int.from_bytes(fm[app_state.data_offset:app_state.data_offset+4], byteorder=app_state.byteorder, signed=True)
                uint32 = int.from_bytes(fm[app_state.data_offset:app_state.data_offset+4], byteorder=app_state.byteorder, signed=False)
                int64 = int.from_bytes(fm[app_state.data_offset:app_state.data_offset+8], byteorder=app_state.byteorder, signed=True)
                uint64 = int.from_bytes(fm[app_state.data_offset:app_state.data_offset+8], byteorder=app_state.byteorder, signed=False)
                #[f32] = struct.unpack('f', fm[data_offset:data_offset+4])
                #[f64] = struct.unpack('d', fm[data_offset:data_offset+8])


                data_win.addstr(1, 1, f'INT8    {int8:>32d}')
                data_win.addstr(2, 1, f'UINT8   {uint8:>32d}')
                data_win.addstr(3, 1, f'INT16   {int16:>32d}')
                data_win.addstr(4, 1, f'UINT16  {uint16:>32d}')
                data_win.addstr(5, 1, f'INT32   {int32:>32d}')
                data_win.addstr(6, 1, f'UINT32  {uint32:>32d}')
                data_win.addstr(7, 1, f'INT64   {int64:>32d}')
                data_win.addstr(8, 1, f'UINT64  {uint64:>32d}')
                data_win.addstr(9, 1, f'EPOCH   {datetime.datetime.fromtimestamp(uint32).strftime("%c"):>32}')

                #data_win.addstr(9, 1, f'F32     {f32:1.10f}')
                #data_win.addstr(10, 1, f'F64     {str(f64)[:20]}')


                mark_win.box()
                mark_win.addstr(0, (screen_sizing.mark_win_width//2) - 4, 'File marks')
                for i,mark in enumerate(app_state.marks):
                    mark_win.addstr(1+i, 1, f'0x{mark:012X}    {(app_state.data_offset-mark):22d}')

                if app_state.struct_eval:
                    real_position: int = app_state.data_offset
                    eval_size = struct.calcsize(app_state.struct_eval)
                    try:
                        eval_data = struct.unpack(app_state.struct_eval, fm[real_position:real_position+eval_size])
                        for i,data in enumerate(eval_data):
                            if isinstance(data, bytes):
                                eval_win.addstr(2+i, 1, ' ' * (screen_sizing.eval_win_width-4))
                                eval_win.addstr(2+i, 1, f'{i:<3d} {_buffer_as_printable(data)}')
                            else:
                                eval_win.addstr(2+i, 1, f'{i:<3d} {data:<{screen_sizing.eval_win_width-8}d}')
                    except:
                        eval_win.addstr(2, 1, '*Error*')

                data_win.refresh()
                dump_win.refresh()
                mark_win.refresh()
                eval_win.refresh()
                stdscr.refresh()

                keypress = stdscr.getch()
                if keypress == curses.KEY_DOWN:
                    # down
                    if cy > (screen_sizing.dump_win_height-3):
                        app_state.file_offset += screen_sizing.bytes_per_line
                    else:
                        app_state.cursor_position += screen_sizing.bytes_per_line
                elif keypress == curses.KEY_UP:
                    # up

                    if cy < 2:
                        app_state.file_offset -= screen_sizing.bytes_per_line
                    else:
                        app_state.cursor_position -= screen_sizing.bytes_per_line
                elif keypress == curses.KEY_LEFT:
                    # left
                    app_state.cursor_position -= 1
                    if cy < 2:
                        if app_state.mode == MODE_HEX:
                            if cx <= screen_sizing.hex_offset:
                                app_state.file_offset -= screen_sizing.bytes_per_line
                                app_state.cursor_position += screen_sizing.bytes_per_line
                        else:
                            if cx <= screen_sizing.ascii_offset:
                                app_state.file_offset -= screen_sizing.bytes_per_line
                                app_state.cursor_position += screen_sizing.bytes_per_line
                elif keypress == curses.KEY_RIGHT:
                    # right
                    app_state.cursor_position += 1
                    if cy > (screen_sizing.dump_win_height-3):
                        if app_state.mode == MODE_HEX:
                            if cx >= screen_sizing.ascii_offset - 4:
                                app_state.file_offset += screen_sizing.bytes_per_line
                                app_state.cursor_position -= screen_sizing.bytes_per_line
                        else:
                            if cx > screen_sizing.ascii_offset + screen_sizing.bytes_per_line - 2:
                                app_state.file_offset += screen_sizing.bytes_per_line
                                app_state.cursor_position -= screen_sizing.bytes_per_line

                elif keypress == 9:
                    # TAB switch window
                    app_state.mode = MODE_HEX if app_state.mode == MODE_ASCII else MODE_ASCII
                elif keypress == curses.KEY_NPAGE:
                    # PGDN next screen
                    app_state.file_offset += screen_sizing.bytes_per_screen
                    dump_win.clear()
                elif keypress == curses.KEY_PPAGE:
                    # PGUP previous screen
                    app_state.file_offset -= screen_sizing.bytes_per_screen
                    dump_win.clear()
                elif keypress in [44, 60]:
                    # < jump to start
                    app_state.cursor_position = 0
                    app_state.file_offset = 0
                    dump_win.clear()
                elif keypress in [46, 62]:
                    # > jump to end
                    app_state.file_offset = file_size // screen_sizing.bytes_per_screen * screen_sizing.bytes_per_screen
                    app_state.cursor_position = file_size % screen_sizing.bytes_per_screen
                    app_state.cursor_position -= 1
                    dump_win.clear()
                elif keypress == 10:
                    # ENTER Jump to position
                    jump_win = curses.newwin(3, 60, screen_sizing.dump_win_height//2 - 1, screen_sizing.dump_win_width//2 - 30)
                    jump_win.box()
                    jump_win.addstr(0, 22, "Jump to position")
                    jump_win.addstr(1, 2, "0x")
                    jump_win.refresh()

                    curses.echo()
                    location = jump_win.getstr()
                    curses.noecho()

                    try:
                        jump_location = int(location, 16)

                        if jump_location > file_size:
                            raise ValueError('Invalid jump location')

                        app_state.cursor_position = jump_location % screen_sizing.bytes_per_screen
                        app_state.file_offset = (jump_location // screen_sizing.bytes_per_screen) * screen_sizing.bytes_per_screen
                    except:
                        pass
                elif keypress == 106:
                    # j set jump
                    jump_win = curses.newwin(3, 60, screen_sizing.dump_win_height//2 - 1, screen_sizing.dump_win_width//2 - 30)
                    jump_win.box()
                    jump_win.addstr(0, 22, "Set Jump Offset")
                    jump_win.addstr(1, 2, "")
                    jump_win.refresh()

                    curses.echo()
                    location = jump_win.getstr()
                    curses.noecho()

                    try:
                        app_state.jump_offset = int(location, 10)
                    except:
                        app_state.jump_offset = 0
                elif keypress == 74:
                    # J set jump
                    jump_win = curses.newwin(3, 60, screen_sizing.dump_win_height//2 - 1, screen_sizing.dump_win_width//2 - 30)
                    jump_win.box()
                    jump_win.addstr(0, 22, "Set Jump Offset")
                    jump_win.addstr(1, 2, "0x")
                    jump_win.refresh()

                    curses.echo()
                    location = jump_win.getstr()
                    curses.noecho()

                    try:
                        app_state.jump_offset = int(location, 16)
                    except:
                        app_state.jump_offset = 0
                elif keypress == 32:
                    # SPACE repeat jump
                    try:
                        new_position: int = app_state.data_offset + app_state.jump_offset
                        if new_position < file_size:
                            app_state.cursor_position = new_position % screen_sizing.bytes_per_screen
                            app_state.file_offset = (new_position // screen_sizing.bytes_per_screen) * screen_sizing.bytes_per_screen
                    except:
                        pass
                elif keypress == 47:
                    # / search
                    if app_state.mode == MODE_ASCII:
                        search_win = curses.newwin(3, 60, screen_sizing.dump_win_height//2 - 1, screen_sizing.dump_win_width//2 - 30)
                        search_win.box()
                        search_win.addstr(0, 19, "ASCII string to search")
                        search_win.addstr(1, 2, "")
                        search_win.refresh()

                        curses.echo()
                        new_ascii_search = search_win.getstr()
                        if new_ascii_search:
                            app_state.ascii_search = new_ascii_search
                        curses.noecho()

                        search_start_position: int = app_state.data_offset + 1
                        search_stop_position: int = search_start_position + search_block_size

                        search_win.erase()
                        if app_state.ascii_search:
                            spinner = _spinning_cursor()

                            search_progress_win = curses.newwin(3, 60, screen_sizing.dump_win_height//2 - 1, screen_sizing.dump_win_width//2 - 30)
                            search_progress_win.box()
                            search_progress_win.addstr(0, 24, "Searching...")

                            search_progress_win.addstr(1, 2, f"{next(spinner)} 0x{search_start_position:0{screen_sizing.offset_address_size}X}/0x{file_size:0{screen_sizing.offset_address_size}X}")
                            search_progress_win.refresh()

                            try:
                                new_position = fm.find(app_state.ascii_search, search_start_position, search_stop_position)
                                while new_position == -1:
                                    search_start_position = search_stop_position
                                    if search_start_position > file_size:
                                        break

                                    search_stop_position = search_start_position + search_block_size
                                    new_position = fm.find(app_state.ascii_search, search_start_position, search_stop_position)
                                    search_progress_win.addstr(1, 2, f"{next(spinner)} 0x{search_start_position:0{screen_sizing.offset_address_size}X}/0x{file_size:0{screen_sizing.offset_address_size}X}")
                                    search_progress_win.refresh()

                                if new_position != -1:
                                    app_state.cursor_position = new_position % screen_sizing.bytes_per_screen
                                    app_state.file_offset = (new_position // screen_sizing.bytes_per_screen) * screen_sizing.bytes_per_screen
                                else:
                                    search_progress_win.addstr(1, 2, " " * 57)
                                    search_progress_win.addstr(1, 2, "Not found.")
                                    search_progress_win.getch()
                            except KeyboardInterrupt:
                                app_state.ascii_search = ''
                                search_progress_win.addstr(1, 2, " " * 57)
                                search_progress_win.addstr(1, 2, "Search cancelled.")
                                search_progress_win.getch()


                    else:
                        search_win = curses.newwin(3, 60, screen_sizing.dump_win_height//2 - 1, screen_sizing.dump_win_width//2 - 30)
                        search_win.box()
                        search_win.addstr(0, 20, "Hex value to search")
                        search_win.addstr(1, 2, "0x")
                        search_win.refresh()

                        curses.echo()
                        new_hex_search = search_win.getstr()
                        if new_hex_search:
                            try:
                                app_state.hex_search = bytes.fromhex(new_hex_search.decode('ascii'))
                            except:
                                app_state.hex_search = b''
                        curses.noecho()


                        search_start_position: int = app_state.data_offset + 1
                        search_stop_position: int = search_start_position + search_block_size

                        search_win.erase()
                        if app_state.hex_search:
                            spinner = _spinning_cursor()

                            search_progress_win = curses.newwin(3, 60, screen_sizing.dump_win_height//2 - 1, screen_sizing.dump_win_width//2 - 30)
                            search_progress_win.box()
                            search_progress_win.addstr(0, 24, "Searching...")

                            search_progress_win.addstr(1, 2, f"{next(spinner)} 0x{search_start_position:0{screen_sizing.offset_address_size}X}/0x{file_size:0{screen_sizing.offset_address_size}X}")
                            search_progress_win.refresh()

                            try:
                                new_position = fm.find(app_state.hex_search, search_start_position, search_stop_position)
                                while new_position == -1:
                                    search_start_position = search_stop_position
                                    if search_start_position > file_size:
                                        break

                                    search_stop_position = search_start_position + search_block_size
                                    new_position = fm.find(app_state.hex_search, search_start_position, search_stop_position)
                                    search_progress_win.addstr(1, 2, f"{next(spinner)} 0x{search_start_position:0{screen_sizing.offset_address_size}X}/0x{file_size:0{screen_sizing.offset_address_size}X}")
                                    search_progress_win.refresh()

                                if new_position != -1:
                                    app_state.cursor_position = new_position % screen_sizing.bytes_per_screen
                                    app_state.file_offset = (new_position // screen_sizing.bytes_per_screen) * screen_sizing.bytes_per_screen
                                else:
                                    search_progress_win.addstr(1, 2, " " * 57)
                                    search_progress_win.addstr(1, 2, "Not found.")
                                    search_progress_win.getch()
                            except KeyboardInterrupt:
                                app_state.hex_search = b''
                                search_progress_win.addstr(1, 2, " " * 57)
                                search_progress_win.addstr(1, 2, "Search cancelled.")
                                search_progress_win.getch()


                elif keypress == 108:
                    # l toggle big/little endian display
                    app_state.byteorder = 'little' if app_state.byteorder == 'big' else 'big'
                elif keypress == 109:
                    # m add file mark
                    if app_state.data_offset not in app_state.marks:
                        app_state.marks.append(app_state.data_offset)

                        while len(app_state.marks) > 10:
                            app_state.marks.pop(0)
                elif keypress == 77:
                    # M remove last file mark
                    if app_state.marks:
                        app_state.marks.pop()
                    mark_win.clear()
                elif keypress == 78:
                    # N jump to previous mark
                    if app_state.marks:
                        next_positions: int = [mark for mark in app_state.marks if mark < app_state.data_offset]

                        new_position: int = next_positions[-1] if next_positions else app_state.marks[-1]

                        app_state.cursor_position = new_position % screen_sizing.bytes_per_screen
                        app_state.file_offset = (new_position // screen_sizing.bytes_per_screen) * screen_sizing.bytes_per_screen

                elif keypress == 110:
                    # n jump to next mark
                    if app_state.marks:
                        next_positions: int = [mark for mark in app_state.marks if mark > app_state.data_offset]

                        new_position: int = next_positions[0] if next_positions else app_state.marks[0]

                        app_state.cursor_position = new_position % screen_sizing.bytes_per_screen
                        app_state.file_offset = (new_position // screen_sizing.bytes_per_screen) * screen_sizing.bytes_per_screen
                elif keypress == 115:
                    # s struct eval
                    struct_win = curses.newwin(3, 60, screen_sizing.dump_win_height//2 - 1, screen_sizing.dump_win_width//2 - 30)
                    struct_win.box()
                    struct_win.addstr(0, 23, "Struct Pattern")
                    struct_win.addstr(1, 2, app_state.struct_eval)
                    char = struct_win.getch()
                    while char != 10:
                        if char == 127:
                            if app_state.struct_eval:
                                app_state.struct_eval = app_state.struct_eval[:-1]
                        else:
                            app_state.struct_eval += chr(char)
                        struct_win.addstr(1, 2 + len(app_state.struct_eval), ' ')
                        struct_win.addstr(1, 2, app_state.struct_eval)
                        char = struct_win.getch()

                    if app_state.struct_eval:
                        eval_win.addstr(1, 1, f'{app_state.struct_eval}  len={(struct.calcsize(app_state.struct_eval))}')
                elif keypress == 91:
                     # [ jump back struct eval number of bytes
                    if app_state.struct_eval:
                        new_position: int = app_state.data_offset - struct.calcsize(app_state.struct_eval)
                        if new_position < file_size:
                            app_state.cursor_position = new_position % screen_sizing.bytes_per_screen
                            app_state.file_offset = (new_position // screen_sizing.bytes_per_screen) * screen_sizing.bytes_per_screen
                elif keypress == 93:
                    # ] jump struct eval number of bytes
                    if app_state.struct_eval:
                        new_position: int = app_state.data_offset + struct.calcsize(app_state.struct_eval)
                        if new_position < file_size:
                            app_state.cursor_position = new_position % screen_sizing.bytes_per_screen
                            app_state.file_offset = (new_position // screen_sizing.bytes_per_screen) * screen_sizing.bytes_per_screen
                elif keypress == curses.KEY_RESIZE:
                    # window resize
                    screen_sizing = ScreenSizing(stdscr, file_size)
                elif keypress == 113:
                    # q quit
                    return
                elif keypress == 104:
                    # h Help
                    _show_help_window(screen_sizing)
                    stdscr.getch()
                    stdscr.refresh()
                else:
                    if args.debug:
                        raise ValueError(keypress)

                app_state.cursor_position = max(app_state.cursor_position, 0)
                app_state.cursor_position = min(app_state.cursor_position, file_size)
                app_state.file_offset = max(app_state.file_offset, 0)
                app_state.file_offset = min(app_state.file_offset, file_size - (file_size % (screen_sizing.bytes_per_line * screen_sizing.dump_win_height-2)))


if __name__ == "__main__":
    try:
        curses.wrapper(main)
    except KeyboardInterrupt:
        pass
